### Pandas 

In [3]:
# !pip install pandas

In [4]:
import numpy as np
import pandas as pd


In [5]:
df=pd.read_csv('Used_Bikes.csv')

In [6]:
df

bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1               Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                      Triumph Daytona 675R  600000.0      Delhi       110.0   
3                      TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                     ...       ...        ...         ...   
32643                Hero Passion Pro 100cc   39000.0      Delhi     22000.0   
32644                  TVS Apache RTR 180cc   30000.0     Karnal      6639.0   
32645              Bajaj Avenger Street 220   60000.0      Delhi     20373.0   
32646             Hero Super Splendor 125cc   15600.0     Jaipur     84186.0   
32647                    Bajaj Pulsar 150cc   22000.0       Pune     60857.0   

             owner   age  power          brand  
0      First Owner   3.0  110.0            TVS  
1      First Owner   4.0  350.0  Royal Enfield  
2      First Owner   8.0  675.0        Triumph  
3      First Owner   4.0  180.0            TVS  
4      First Owner   3.0  150.0         Yamaha  
...            ...   ...    ...            ...  
32643  First Owner   4.0  100.0           Hero  
32644  First Owner   9.0  180.0            TVS  
32645  First Owner   6.0  220.0          Bajaj  
32646  First Owner  16.0  125.0           Hero  
32647  First Owner  13.0  150.0          Bajaj  

[32648 rows x 8 columns]

In [7]:
dataset_path=r"C:\Users\kumaw\OneDrive\Desktop\1 may data science\Stip_data-science-1st-may-\pandas\Used_Bikes.csv"

In [8]:
# df=pd.read_csv(dataset_path)

In [9]:
df

bike_name     price       city  kms_driven  \
0        TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1               Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                      Triumph Daytona 675R  600000.0      Delhi       110.0   
3                      TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4      Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   
...                                     ...       ...        ...         ...   
32643                Hero Passion Pro 100cc   39000.0      Delhi     22000.0   
32644                  TVS Apache RTR 180cc   30000.0     Karnal      6639.0   
32645              Bajaj Avenger Street 220   60000.0      Delhi     20373.0   
32646             Hero Super Splendor 125cc   15600.0     Jaipur     84186.0   
32647                    Bajaj Pulsar 150cc   22000.0       Pune     60857.0   

             owner   age  power          brand  
0      First Owner   3.0  110.0            TVS  
1      First Owner   4.0  350.0  Royal Enfield  
2      First Owner   8.0  675.0        Triumph  
3      First Owner   4.0  180.0            TVS  
4      First Owner   3.0  150.0         Yamaha  
...            ...   ...    ...            ...  
32643  First Owner   4.0  100.0           Hero  
32644  First Owner   9.0  180.0            TVS  
32645  First Owner   6.0  220.0          Bajaj  
32646  First Owner  16.0  125.0           Hero  
32647  First Owner  13.0  150.0          Bajaj  

[32648 rows x 8 columns]

In [10]:
df.head() # top 5 rows

bike_name     price       city  kms_driven  \
0    TVS Star City Plus Dual Tone 110cc   35000.0  Ahmedabad     17654.0   
1           Royal Enfield Classic 350cc  119900.0      Delhi     11000.0   
2                  Triumph Daytona 675R  600000.0      Delhi       110.0   
3                  TVS Apache RTR 180cc   65000.0  Bangalore     16329.0   
4  Yamaha FZ S V 2.0 150cc-Ltd. Edition   80000.0  Bangalore     10000.0   

         owner  age  power          brand  
0  First Owner  3.0  110.0            TVS  
1  First Owner  4.0  350.0  Royal Enfield  
2  First Owner  8.0  675.0        Triumph  
3  First Owner  4.0  180.0            TVS  
4  First Owner  3.0  150.0         Yamaha

In [11]:
df.tail() # bottom 5 rows

bike_name    price    city  kms_driven        owner  \
32643     Hero Passion Pro 100cc  39000.0   Delhi     22000.0  First Owner   
32644       TVS Apache RTR 180cc  30000.0  Karnal      6639.0  First Owner   
32645   Bajaj Avenger Street 220  60000.0   Delhi     20373.0  First Owner   
32646  Hero Super Splendor 125cc  15600.0  Jaipur     84186.0  First Owner   
32647         Bajaj Pulsar 150cc  22000.0    Pune     60857.0  First Owner   

        age  power  brand  
32643   4.0  100.0   Hero  
32644   9.0  180.0    TVS  
32645   6.0  220.0  Bajaj  
32646  16.0  125.0   Hero  
32647  13.0  150.0  Bajaj

In [12]:
df.info() # info about data


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   bike_name   32648 non-null  object 
 1   price       32648 non-null  float64
 2   city        32648 non-null  object 
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  object 
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  object 
dtypes: float64(4), object(4)
memory usage: 2.0+ MB


In [13]:
df.describe() # summary of data

price     kms_driven           age         power
count  3.264800e+04   32648.000000  32648.000000  32648.000000
mean   6.829542e+04   26344.625184      8.048211    213.511302
std    9.071860e+04   22208.527695      4.031700    134.428868
min    4.400000e+03       1.000000      1.000000    100.000000
25%    2.500000e+04   12000.000000      5.000000    150.000000
50%    4.300000e+04   20373.000000      7.000000    150.000000
75%    8.000000e+04   35000.000000     10.000000    220.000000
max    1.900000e+06  750000.000000     63.000000   1800.000000

In [14]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [15]:
df.duplicated().sum()

25324

In [16]:
32648-25324

7324

In [17]:
df.drop_duplicates(inplace=True) # drop duplicates

In [18]:
df.duplicated().sum()

0

In [19]:
print("unique values:-",df['bike_name'].unique())
print("number of unique values:-",df['bike_name'].nunique())

unique values:- ['TVS Star City Plus Dual Tone 110cc' 'Royal Enfield Classic 350cc'
 'Triumph Daytona 675R' 'TVS Apache RTR 180cc'
 'Yamaha FZ S V 2.0 150cc-Ltd. Edition' 'Yamaha FZs 150cc'
 'Honda CB Hornet 160R  ABS DLX' 'Hero Splendor Plus Self Alloy 100cc'
 'Royal Enfield Thunderbird X 350cc'
 'Royal Enfield Classic Desert Storm 500cc' 'Yamaha YZF-R15 2.0 150cc'
 'Yamaha FZ25 250cc' 'Bajaj Pulsar NS200' 'Bajaj Discover 100M'
 'Bajaj Discover 125M' 'Bajaj Pulsar NS200 ABS' 'Bajaj Pulsar RS200 ABS'
 'Suzuki Gixxer SF 150cc' 'Benelli 302R 300CC'
 'Hero Splendor iSmart Plus IBS 110cc'
 'Royal Enfield Classic Chrome 500cc' 'Yamaha FZ V 2.0 150cc'
 'Hero Super Splendor 125cc' 'Honda CBF Stunner 125cc'
 'Bajaj Pulsar 150cc' 'Honda X-Blade 160CC ABS' 'Bajaj Avenger 220cc'
 'KTM RC 390cc' 'Honda CB Unicorn 150cc' 'KTM Duke 200cc'
 'Honda CBR 150R 150cc' 'Royal Enfield Thunderbird X 500cc'
 'KTM RC 200cc ABS' 'Royal Enfield Thunderbird 350cc'
 'Royal Enfield Bullet Electra 350cc' 'Bajaj Aven

In [20]:
print("unique values of brand :-",df['brand'].unique())
print("total unique values of brand :-",df['brand'].nunique())

unique values of brand :- ['TVS' 'Royal Enfield' 'Triumph' 'Yamaha' 'Honda' 'Hero' 'Bajaj' 'Suzuki'
 'Benelli' 'KTM' 'Mahindra' 'Kawasaki' 'Ducati' 'Hyosung'
 'Harley-Davidson' 'Jawa' 'BMW' 'Indian' 'Rajdoot' 'LML' 'Yezdi' 'MV'
 'Ideal']
total unique values of brand :- 23


In [21]:
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth Owner Or More'], dtype=object)

In [22]:
df['owner'].value_counts()

owner
First Owner             6642
Second Owner             588
Third Owner               84
Fourth Owner Or More      10
Name: count, dtype: int64

In [23]:
# two part data set 
# price and baki ke columns alg liye 

In [24]:
df =df.drop(['city','bike_name'],axis=1) # drop columns

In [25]:
df 


price  kms_driven        owner  age  power            brand
0      35000.0     17654.0  First Owner  3.0  110.0              TVS
1     119900.0     11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0       110.0  First Owner  8.0  675.0          Triumph
3      65000.0     16329.0  First Owner  4.0  180.0              TVS
4      80000.0     10000.0  First Owner  3.0  150.0           Yamaha
...        ...         ...          ...  ...    ...              ...
9362   25000.0     48587.0  First Owner  8.0  150.0             Hero
9369   35000.0     60000.0  First Owner  9.0  220.0            Bajaj
9370  450000.0      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0  First Owner  4.0  400.0            Bajaj
9372   80000.0      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [26]:
cat_cols=df.select_dtypes(include='object')

In [27]:
cat_cols

owner            brand
0     First Owner              TVS
1     First Owner    Royal Enfield
2     First Owner          Triumph
3     First Owner              TVS
4     First Owner           Yamaha
...           ...              ...
9362  First Owner             Hero
9369  First Owner            Bajaj
9370  First Owner  Harley-Davidson
9371  First Owner            Bajaj
9372  First Owner            Bajaj

[7324 rows x 2 columns]

In [28]:
num_cols=df.select_dtypes(exclude='object')

In [29]:
num_cols

price  kms_driven  age  power
0      35000.0     17654.0  3.0  110.0
1     119900.0     11000.0  4.0  350.0
2     600000.0       110.0  8.0  675.0
3      65000.0     16329.0  4.0  180.0
4      80000.0     10000.0  3.0  150.0
...        ...         ...  ...    ...
9362   25000.0     48587.0  8.0  150.0
9369   35000.0     60000.0  9.0  220.0
9370  450000.0      3430.0  4.0  750.0
9371  139000.0     21300.0  4.0  400.0
9372   80000.0      7127.0  5.0  220.0

[7324 rows x 4 columns]

In [30]:
cat_cols['owner'].unique()

array(['First Owner', 'Second Owner', 'Third Owner',
       'Fourth Owner Or More'], dtype=object)

In [31]:
ower_dict={'First Owner':0,'Second Owner':1,'Third Owner':2,'Fourth Owner Or More':3}

In [32]:
ower_dict

{'First Owner': 0,
 'Second Owner': 1,
 'Third Owner': 2,
 'Fourth Owner Or More': 3}

In [33]:
cat_cols['owner']=cat_cols['owner'].map(ower_dict)

In [34]:
cat_cols['owner'].unique()

array([0, 1, 2, 3], dtype=int64)

In [35]:
cat_cols['brand'].unique()  

array(['TVS', 'Royal Enfield', 'Triumph', 'Yamaha', 'Honda', 'Hero',
       'Bajaj', 'Suzuki', 'Benelli', 'KTM', 'Mahindra', 'Kawasaki',
       'Ducati', 'Hyosung', 'Harley-Davidson', 'Jawa', 'BMW', 'Indian',
       'Rajdoot', 'LML', 'Yezdi', 'MV', 'Ideal'], dtype=object)

In [36]:
brand_dict ={'TVS':0, 'Royal Enfield':1, 'Triumph':2, 'Yamaha':3, 'Honda':4, 'Hero':5,
       'Bajaj':6, 'Suzuki':7, 'Benelli':8, 'KTM':9, 'Mahindra':10, 'Kawasaki':11,
       'Ducati':12, 'Hyosung':13, 'Harley-Davidson':14, 'Jawa':15, 'BMW':16, 'Indian':17,
       'Rajdoot':18, 'LML':19, 'Yezdi':20, 'MV':21, 'Ideal':22}

In [37]:
cat_cols['brand']=cat_cols['brand'].map(brand_dict)

In [38]:
cat_cols

owner  brand
0         0      0
1         0      1
2         0      2
3         0      0
4         0      3
...     ...    ...
9362      0      5
9369      0      6
9370      0     14
9371      0      6
9372      0      6

[7324 rows x 2 columns]

In [39]:
complete_df =pd.concat([cat_cols,num_cols],axis=1)

In [40]:
complete_df

owner  brand     price  kms_driven  age  power
0         0      0   35000.0     17654.0  3.0  110.0
1         0      1  119900.0     11000.0  4.0  350.0
2         0      2  600000.0       110.0  8.0  675.0
3         0      0   65000.0     16329.0  4.0  180.0
4         0      3   80000.0     10000.0  3.0  150.0
...     ...    ...       ...         ...  ...    ...
9362      0      5   25000.0     48587.0  8.0  150.0
9369      0      6   35000.0     60000.0  9.0  220.0
9370      0     14  450000.0      3430.0  4.0  750.0
9371      0      6  139000.0     21300.0  4.0  400.0
9372      0      6   80000.0      7127.0  5.0  220.0

[7324 rows x 6 columns]

In [41]:
x =complete_df.drop('price', axis=1)
y =complete_df[['price']]


In [42]:
x   ###>>>>>>>>>>>>>>>>.. independent variables

owner  brand  kms_driven  age  power
0         0      0     17654.0  3.0  110.0
1         0      1     11000.0  4.0  350.0
2         0      2       110.0  8.0  675.0
3         0      0     16329.0  4.0  180.0
4         0      3     10000.0  3.0  150.0
...     ...    ...         ...  ...    ...
9362      0      5     48587.0  8.0  150.0
9369      0      6     60000.0  9.0  220.0
9370      0     14      3430.0  4.0  750.0
9371      0      6     21300.0  4.0  400.0
9372      0      6      7127.0  5.0  220.0

[7324 rows x 5 columns]

In [43]:
y   ###>>>>>>>>>>>>>>>> dependent variables

price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
9362   25000.0
9369   35000.0
9370  450000.0
9371  139000.0
9372   80000.0

[7324 rows x 1 columns]

In [44]:
# !pip install scikit-learn

In [45]:
# train and test split

# train model or testing model

from sklearn.model_selection import  train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [46]:
from sklearn.ensemble import RandomForestRegressor
import joblib
rfc=RandomForestRegressor()
rfc.fit(x_train,y_train)
joblib.dump(rfc,'model.joblib')



c:\Users\kumaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


['model.joblib']

In [44]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((5859, 5), (1465, 5), (5859, 1), (1465, 1))

In [45]:
from sklearn.linear_model import LinearRegression

In [46]:
lr =LinearRegression()

In [47]:
lr.fit(x_train,y_train)

LinearRegression()

In [48]:
lr.score(x_test,y_test)

0.7530846908957206

In [49]:
lr.score(x_train,y_train)

0.7104324344011279

In [50]:
pred =lr.predict(x_test)

In [51]:
predidiction_histroy ={"predicted_price":pred,"actual_price":y_test}

In [52]:
# lst =list(y_test)
pred=pd.DataFrame(pred)

In [53]:
pd.concat([pred,y_test],axis=1)

0     price
0      30257.531368       NaN
1     140716.911081  119900.0
2      -9704.035621       NaN
3     107427.680714       NaN
4      28235.120355       NaN
...             ...       ...
5389            NaN  105000.0
7667            NaN   25000.0
6258            NaN   25000.0
8943            NaN   20000.0
6858            NaN   70000.0

[2700 rows x 2 columns]

In [54]:
# pd.DataFrame(predidiction_histroy)

In [55]:
from sklearn.svm import SVR 

In [56]:
svr_obj=SVR()

In [57]:
svr_obj.fit(x_train,y_train)

c:\Users\kumaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [58]:
svr_obj.score(x_test,y_test)

-0.07184108083361518

In [59]:
svr_obj.score(x_train,y_train)

-0.05828152912902218

### Knn
* KNN (K-Nearest Neighbors) is a simple, non-parametric machine learning algorithm used for classification and regression tasks. It’s based on the idea that data points that are close to each other are likely to have similar outcomes.

🔍 How It Works:
Choose a value of K (number of neighbors to consider).

Measure the distance between the new input and all the points in the training dataset (commonly using Euclidean distance).

Identify the K closest neighbors to the new data point.

For:

Classification: The new point is assigned the most common class among its K neighbors (majority vote).

Regression: The output is the average of the values of the K nearest neighbors.

In [60]:
from sklearn.neighbors import KNeighborsClassifier ,KNeighborsRegressor

In [61]:
knr =KNeighborsRegressor()

In [62]:
knr.fit(x_train , y_train)

KNeighborsRegressor()

In [63]:
print("testing score :-",knr.score(x_test,y_test))

testing score :- 0.6239911003208788


In [64]:
print("training score :-",knr.score(x_train,y_train))

training score :- 0.7854018315459385


In [65]:
knr.predict(x_test)

array([[ 40838.],
       [112740.],
       [ 54000.],
       ...,
       [ 37000.],
       [ 33960.],
       [ 61600.]])

### DT
DT stands for Decision Tree, a popular machine learning algorithm used for classification and regression tasks. It's a supervised learning method that works by learning simple decision rules inferred from data features.

🌳 What Is a Decision Tree?
A Decision Tree is a flowchart-like structure where:

Each internal node represents a feature (or attribute).

Each branch represents a decision rule.

Each leaf node represents an outcome (class label or value).

In [66]:
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier

In [67]:
dtr =DecisionTreeRegressor()

In [68]:
dtr.fit(x_train,y_train)

DecisionTreeRegressor()

In [69]:
print("testing score :-",dtr.score(x_test,y_test))

testing score :- 0.8168238056559496


In [70]:
print("traning score :-",dtr.score(x_train,y_train))



traning score :- 0.9980046623640842


In [71]:
df =pd.read_csv("https://raw.githubusercontent.com/upflairs-pvt-ltd/3rd_july_datascience/master/farmer_guider/farmer.csv ")

In [72]:
df

N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]

In [73]:
dtr.predict(x_test)

array([ 33000., 140000.,  30000., ...,  29500.,  18000., 110000.])

#### Ramdomforest 
Random Forest: Random Forest is an extension over bagging. Each classifier in the ensemble is a decision tree classifier and is generated using a random selection of attributes at each node to determine the split. During classification, each tree votes and the most popular class is returned. Implementation steps of Random Forest -
Multiple subsets are created from the original data set, selecting observations with replacement.

A subset of features is selected randomly and whichever feature gives the best split is used to split the node iteratively.

The tree is grown to the largest.

Repeat the above steps and prediction is given based on the aggregation of predictions from n number of trees.

In [74]:
from sklearn.ensemble import  RandomForestRegressor , RandomForestClassifier

In [75]:
rfr =RandomForestRegressor()

In [76]:
rfr.fit(x_train,y_train)

c:\Users\kumaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1474: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestRegressor()

In [77]:
rfr.score(x_test,y_test)

0.9178940176542459

In [78]:
rfr.score(x_train,y_train)

0.9839550989804912

In [ ]:
# laptop prediction
# bike prediction
# crop 
# loyal and disloyal 
# house price predication 



### Naive Bayes 


In [ ]:
from sklearn.naive_bayes import GaussianNB , MultinomialNB, BernoulliNB
gnb =GaussianNB()
gnb.fit(x_train,y_train)
print("testing score :-",gnb.score(x_test,y_test))
print("training score :-",gnb.score(x_train,y_train))


c:\Users\kumaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


testing score :- 0.021843003412969283
training score :- 0.16999487967229904


In [81]:
from sklearn.datasets import load_iris
data =load_iris()
x =data.data
y =data.target

In [82]:
x  

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [83]:
y 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [84]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
from sklearn.naive_bayes import BernoulliNB
gnb =BernoulliNB()
gnb.fit(x_train,y_train)
print("testing score :-",gnb.score(x_test,y_test))
print("training score :-",gnb.score(x_train,y_train))

testing score :- 0.26666666666666666
training score :- 0.35


In [86]:
from sklearn.ensemble import RandomForestRegressor
rf =RandomForestRegressor()
rf.fit(x_train,y_train)
print("testing score :-",rf.score(x_test,y_test))
print("training score :-",rf.score(x_train,y_train))

testing score :- 0.9679144385026738
training score :- 0.9920543713314798


In [87]:
import joblib 


joblib.dump(rf ,  "bike_price.joblib")

['bike_price.joblib']

In [88]:
model =joblib.load("bike_price.joblib")

In [89]:
pred =model.predict(x_test)

In [90]:
pred

array([1.98, 1.23, 2.  , 2.  , 1.  , 0.  , 1.94, 2.  , 1.  , 1.02, 1.  ,
       1.  , 0.  , 0.  , 1.95, 2.  , 1.  , 1.01, 2.  , 1.  , 0.  , 0.  ,
       0.  , 2.  , 1.  , 2.  , 1.  , 0.  , 0.  , 1.01])

In [91]:
predidiction_histroy ={"predicted_price":pred,"actual_price":y_test}

In [93]:
pd.DataFrame(predidiction_histroy)

predicted_price  actual_price
0              1.98             2
1              1.23             2
2              2.00             2
3              2.00             2
4              1.00             1
5              0.00             0
6              1.94             2
7              2.00             2
8              1.00             1
9              1.02             1
10             1.00             1
11             1.00             1
12             0.00             0
13             0.00             0
14             1.95             2
15             2.00             2
16             1.00             1
17             1.01             1
18             2.00             2
19             1.00             1
20             0.00             0
21             0.00             0
22             0.00             0
23             2.00             2
24             1.00             1
25             2.00             2
26             1.00             1
27             0.00             0
28             0.00             0
29             1.01             1